### ISSUE TITLE
Replace ERB with Haml everywhere

### ISSUE THREAD

**Issue by Mehonoshin** [omniscrapper/omniscrapper_hq#15]
Let's stick to a single template engine, and it would be haml

**Comment by romasks** [comment]
@Mehonoshin  I'll take it.

**Comment by Mehonoshin** [comment]
@romasks do it!

**Comment by romasks** [comment]
@Mehonoshin as I understand, you started doing this?

**Comment by Mehonoshin** [comment]
@romasks no, I just assigned you to this issue

**Comment by romasks** [comment]
It's because of I see only `haml` files in `apps/web/template`

**Comment by Mehonoshin** [comment]
@romasks 
https://github.com/omniscrapper/omniscrapper_hq/blob/master/apps/web/templates/application.html.erb
https://github.com/omniscrapper/omniscrapper_hq/blob/master/apps/web/templates/outputs/create.html.erb
https://github.com/omniscrapper/omniscrapper_hq/blob/master/apps/web/templates/single_run/create.html.erb

two of them are empty, but anyway.

Also you can make https://github.com/omniscrapper/omniscrapper_hq/issues/51, it is also related to ERB and should fix the reason why we have those erbs

**Comment by romasks** [comment]
@Mehonoshin thanks, this is what I wanted to know.

And yes, you can assign me to #51

**Comment by romasks** [comment]
@Mehonoshin there is some problem with our `sassc`:
```
SassC::SyntaxError: Error: File to import not found or unreadable: config/fonts.
        on line 1 of stdin
>> @import "config/fonts";
```
[The fix of this problem](https://github.com/sass/sassc-ruby/pull/81)
So I propose to use the newest version of the gem - `2.2.1`. But it can be only problem on my environment.

**Comment by Mehonoshin** [comment]
I didn't see this error on my machine.
@ArtemRakov did you?

But anyway downgrading is not a way to go, try to fix it locally first.

**Comment by ArtemRakov** [comment]
No, I don't have this error.

**Comment by romasks** [comment]
Yes, downgrading is bad idea, but it was old solution. 
Now I talk about _upgrading_ `sassc` to newest version.
But first I'll check it on my linux machine (the problem occurs on my windows machine).

**Comment by romasks** [comment]
@Mehonoshin  I've just create PR #56

**Comment by Mehonoshin** [comment]
Solved, thanks @romasks !
