### ISSUE TITLE
Force hanami to generate haml views instead of ERB by default

### ISSUE THREAD

**Issue by Mehonoshin** [omniscrapper/omniscrapper_hq#51]
Find how to force hanami to use haml by default, at the moment we have to rename templates from erb to haml every time we generate new action.

**Comment by Mehonoshin** [comment]
@romasks takes it

**Comment by romasks** [comment]
@Mehonoshin okay

**Comment by romasks** [comment]
@Mehonoshin done in #68

**Comment by Mehonoshin** [comment]
Solved! Thanks to @romasks 🎉
